version: "2"

services:
  app:
    container_name: employee-service
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "employeesdb"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
